/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        ink: "#1C2430",
        slate: "#5B6B7A",
        fog: "#EEF1F3",
        panel: "#FFFFFF",
        available: "#2E7D5B",
        allocated: "#3B6C93",
        pending: "#C68A2E",
        blocked: "#B23B2E",
        "tag-line": "#0F172A",
        surface: "#fcf8f9",
        "surface-container": "#f0edee",
        "surface-container-low": "#f6f3f4",
        "surface-container-high": "#eae7e8",
        "surface-container-highest": "#e4e2e3",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9da",
        "surface-variant": "#e4e2e3",
        "surface-bright": "#fcf8f9",
        "on-surface": "#1b1b1c",
        "on-surface-variant": "#45474c",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#141c28",
        "on-primary-fixed-variant": "#3f4754",
        "on-primary-container": "#838b9a",
        "primary": "#060e1a",
        "primary-container": "#1c2430",
        "primary-fixed": "#dbe3f3",
        "primary-fixed-dim": "#bfc7d7",
        "secondary": "#50606f",
        "secondary-container": "#d1e2f3",
        "secondary-fixed": "#d4e4f6",
        "secondary-fixed-dim": "#b8c8d9",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#546473",
        "on-secondary-fixed": "#0d1d2a",
        "on-secondary-fixed-variant": "#394856",
        "tertiary": "#160c01",
        "tertiary-container": "#2e2110",
        "tertiary-fixed": "#f7dfc4",
        "tertiary-fixed-dim": "#dac3a9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#9b8770",
        "on-tertiary-fixed": "#251909",
        "on-tertiary-fixed-variant": "#544431",
        "outline": "#75777c",
        "outline-variant": "#c5c6cc",
        "inverse-surface": "#303031",
        "inverse-on-surface": "#f3f0f1",
        "inverse-primary": "#bfc7d7",
        "surface-tint": "#575f6d",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fcf8f9",
        "on-background": "#1b1b1c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "sidebar-width": "240px",
        "stack-lg": "1.5rem",
        "margin-main": "2rem",
        gutter: "1.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Archivo", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "label-mono": ['"IBM Plex Mono"', "monospace"],
        "headline-lg": ["Archivo", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Archivo", "sans-serif"],
        "display-kpi": ["Archivo", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-mono": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "display-kpi": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
