{
    "name": "AssetFlow ERP",
    "version": "17.0.1.0.0",
    "summary": "Enterprise asset and resource management for the Odoo Hackathon",
    "category": "Operations/Inventory",
    "author": "Aeon Core",
    "license": "LGPL-3",
    "depends": ["base", "mail", "hr", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/asset_sequence.xml",
        "data/ir_cron.xml",
        "views/menu.xml",
        "views/department_views.xml",
        "views/asset_views.xml",
        "views/allocation_views.xml",
        "views/booking_views.xml",
        "views/maintenance_views.xml",
        "views/audit_views.xml",
        "views/kpi_dashboard.xml",
    ],
    "application": True,
    "installable": True,
}
