from . import asset_activity_log
from . import asset_notification
from . import base_mixin
from . import res_users
from . import department
from . import employee
from . import asset_category
from . import asset
from . import asset_allocation
from . import asset_transfer
from . import asset_booking
from . import maintenance_request
from . import audit_cycle
from . import audit_mark
from . import dashboard
